### PR TITLE
Adds rich pictures and their source

### LINKED ISSUE #8: Create rich pictures

### PR DESCRIPTION
**Pull request by SebastianMygind**
Please give feedback on them all.
@MadsHeilmann. These are probably most relevant under your section "The Current Situation". Do you want to add them yourself or should I?

### CODE REVIEW

**Comment by SebastianMygind** [comment]
1000 line .drawio.... nice, should i just remove the source.

**Review by audio-engineer — CHANGES_REQUESTED** [review]
@SebastianMygind Issue and issue ID are where?

**Comment by audio-engineer** [comment]
> 1000 line .drawio.... nice, should i just remove the source.

Yes, remove the `.drawio` file. We won't need it here, but upload it to the P3 Teams channel.

**Review by audio-engineer — APPROVED** [review]
Nice, should be sufficient. @MadsHeilmann should some of them in the System Choice chapter.

**Review by MadsHeilmann — APPROVED** [review]

**Review by TexWO — APPROVED** [review]

**Pull request merged**
