### PR TITLE
WIP #96, WIP #97. Add criterion subsection

### PR DESCRIPTION
**Pull request by Danar435**

### CODE REVIEW

**Comment by Danar435** [comment]
@audio-engineer seems like the action is broken

**Comment by audio-engineer** [comment]
@Danar435 GitHub seems to experience some issues. Let's wait for a couple of hours and run it again

**Comment by Danar435** [comment]
@audio-engineer it's still not working

**Comment by audio-engineer** [comment]
@Danar435 I will check it tomorrow

**Comment by audio-engineer** [comment]
@Danar435 Works now

**Review by MadsHeilmann — APPROVED** [review]

**Review by TexWO — APPROVED** [review]

**Pull request merged**
